### ISSUE TITLE
Centerline and 1 color

### ISSUE THREAD

**Issue by Pau-Lozano** [lemonyte/pyautotrace#15]
First of all, huge thanks for making this public, this is amazing job.

I'm not familiar with autotrace, so this is probably a basic question.
When using the centerline algorithm and setting the max number of colors to 0, I always get the same output no matter what the input image is.

Here it is:
<img width="490" alt="Screenshot 2024-02-22 at 16 09 39" src="https://github.com/lemonyte/pyautotrace/assets/48140294/cfea6955-c1f7-4825-99d8-e4ae9b8ec712">

Am I missing something? is this an expected behaviour?
If so, I would truly appreciate some guidance.

Again, thank you for sharing this.

**Comment by lemonyte** [comment]
This does seem to happen with `centerline=True` and `color_count=1`. It would be best to open this issue in the upstream repository https://github.com/autotrace/autotrace since this project doesn't modify autotrace's behavior.
