### ISSUE TITLE
 ValueError: 'autotrace/_autotrace.pyx' doesn't match any files

### ISSUE THREAD

**Issue by rofemen** [lemonyte/pyautotrace#2]
An installation dependency error occurred after packaging
![image](https://user-images.githubusercontent.com/17958671/216933373-36a3f89b-c878-4120-b006-985be6db1c73.png)

**Comment by lemonyte** [comment]
Hey @rofemen! Could you please reply with some information about your system and Python installation?
(OS type & version, Python implementation & version, and any other relevant info)
Thanks!

**Comment by rofemen** [comment]
> Hey @rofemen! Could you please reply with some information about your system and Python installation? (OS type & version, Python implementation & version, and any other relevant info) Thanks!

mac m1 , python version 3.8

**Comment by lemonyte** [comment]
I don't have access to an M1 Mac to build a distribution for that platform, so until I set up automated multi-platform builds, please try building it from source yourself following the instructions [here](https://github.com/lemonyte/pyautotrace#building). Let me know if you encounter any further issues.

**Comment by lemonyte** [comment]
@rofemen this should be fixed since #3 has been merged. You can install either the sdist or wheel for your platform using the artifacts from [this workflow run](https://github.com/lemonyte/pyautotrace/actions/runs/4334582403), or build on your machine. Let me know if it works.

**Comment by 00sapo** [comment]
Hello, it looks like the artifacts have expired. Moreover, you could put them on pypi.org...

**Comment by lemonyte** [comment]
@00sapo I've uploaded newly built wheels for Windows and Linux to PyPI. macOS seems to be having issues with the GLib version, so if you are running a Mac, the solution for now is to install from source and possibly install an earlier version of GLib (~2.34). I'll be closing this issue now, since the original author has not responded for a few months.
