### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jonasostrom** [lemonyte/pyautotrace#4]
python -m pip install pyautotrace

Collecting pyautotrace
  Using cached pyautotrace-0.0.3.tar.gz (411 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyautotrace
  Building wheel for pyautotrace (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyautotrace (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.7-x86_64-cpython-39
      creating build/lib.macosx-11.7-x86_64-cpython-39/autotrace
      copying autotrace/autotrace.py -> build/lib.macosx-11.7-x86_64-cpython-39/autotrace
      copying autotrace/__init__.py -> build/lib.macosx-11.7-x86_64-cpython-39/autotrace
      running egg_info
      writing pyautotrace.egg-info/PKG-INFO
      writing dependency_links to pyautotrace.egg-info/dependency_links.txt
      writing top-level names to pyautotrace.egg-info/top_level.txt
      dependency /usr/local/Cellar/glib/2.78.1/include/glib-2.0/glib.h won't be automatically included in the manifest: the path must be relative
      reading manifest file 'pyautotrace.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'pyautotrace.egg-info/SOURCES.txt'
      copying autotrace/py.typed -> build/lib.macosx-11.7-x86_64-cpython-39/autotrace
      running build_ext
      building 'autotrace._autotrace' extension
      creating build/temp.macosx-11.7-x86_64-cpython-39
      creating build/temp.macosx-11.7-x86_64-cpython-39/autotrace
      creating build/temp.macosx-11.7-x86_64-cpython-39/third-party
      creating build/temp.macosx-11.7-x86_64-cpython-39/third-party/autotrace
      creating build/temp.macosx-11.7-x86_64-cpython-39/third-party/autotrace/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3 -DAUTOTRACE_VERSION=\"0.40.0\" -DAUTOTRACE_WEB=\"https://github.com/autotrace/autotrace\" -DHAVE_MAGICK_READERS=1 -DGLIB_STATIC_COMPILATION=1 -I./third-party/autotrace/src -I/usr/local/Cellar/glib/2.78.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.78.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.42/include -I/Users/Jonas/.pyenv/versions/3.9.18/include/python3.9 -c ./autotrace/_autotrace.c -o build/temp.macosx-11.7-x86_64-cpython-39/./autotrace/_autotrace.o
      ./autotrace/_autotrace.c:3084:33: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        for (__pyx_t_7 = 0; __pyx_t_7 < __pyx_t_6; __pyx_t_7+=1) {
                            ~~~~~~~~~ ^ ~~~~~~~~~
      ./autotrace/_autotrace.c:3238:37: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
          for (__pyx_t_10 = 0; __pyx_t_10 < __pyx_t_9; __pyx_t_10+=1) {
                               ~~~~~~~~~~ ^ ~~~~~~~~~
      2 warnings generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3 -DAUTOTRACE_VERSION=\"0.40.0\" -DAUTOTRACE_WEB=\"https://github.com/autotrace/autotrace\" -DHAVE_MAGICK_READERS=1 -DGLIB_STATIC_COMPILATION=1 -I./third-party/autotrace/src -I/usr/local/Cellar/glib/2.78.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.78.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.42/include -I/Users/Jonas/.pyenv/versions/3.9.18/include/python3.9 -c ./autotrace/overrides.cpp -o build/temp.macosx-11.7-x86_64-cpython-39/./autotrace/overrides.o
      ./autotrace/overrides.cpp:61:12: error: redefinition of 'g_strdup_inline'
          gchar *g_strdup(const gchar *str)
                 ^
      /usr/local/Cellar/glib/2.78.1/include/glib-2.0/glib/gstrfuncs.h:324:21: note: expanded from macro 'g_strdup'
      #define g_strdup(x) g_strdup_inline (x)
                          ^
      /usr/local/Cellar/glib/2.78.1/include/glib-2.0/glib/gstrfuncs.h:309:1: note: previous definition is here
      g_strdup_inline (const char *str)
      ^
      ./autotrace/overrides.cpp:228:19: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                  ext = "";
                        ^
      ./autotrace/overrides.cpp:242:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
              auto it = at_output_formats->find(gsuffix);
              ^
      2 warnings and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyautotrace
Failed to build pyautotrace
ERROR: Could not build wheels for pyautotrace, which is required to install pyproject.toml-based projects

**Comment by lemonyte** [comment]
Hi @jonasostrom! The issue seems to have been caused by the GLib version provided on macOS. I've fixed it and uploaded built wheels to PyPI, so please try installing again. Sorry for the inconvenience and thanks for the report!
